### ISSUE TITLE
Заинтегрить метроник

### ISSUE THREAD

**Issue by puzanov** [maddevsio/spiderwoman#30]
Если при интеграции будут идеи как поменять интерфейс - можно обсуждать и внедрять

**Comment by puzanov** [comment]
@shapoglyk это в приоритете сразу после задачи с выбором типа: #29

**Comment by shapoglyk** [comment]
Для разбивки шаблонов на составляющие:

**Comment by puzanov** [comment]
Каменты после использования 

1. убрать new_index -  пусть будет сразу на индексе обычном
2. с правой стороны шапки пропали ссылки скачивания экселей (сейчас они доступны на странице всех данных за день и новых данных за день). их надо вернуть
3. нужно по умолчанию сделать так, чтобы левое меню шаблона было скрыто. в открытом виде оно не нужно, потому что основа - это таблица, а менюха в открытом виде занимает много места, поэтому ее по умолчанию надо сворачивать 
4. из подвала надо убрать копирайты
5. при клике на лого идет ссылка на несуществующий index.html
6. пока делается календарь, шрифт с датами надо уменьшить, а то их очень много

Как сделаешь, делаем финальный тест в твоей ветке и если все ок, закидываем в мастер и деплоим.

**Comment by puzanov** [comment]
done
