### ISSUE TITLE
Fix crawl test

### ISSUE THREAD

**Issue by puzanov** [maddevsio/spiderwoman#33]
go test -v github.com/maddevsio/spiderwoman -run "^TestCrawl|TestCrawlCaseInsensitive$"
2017/06/17 20:04:59 ERROR parsing URL http://server.com M
2017/06/17 20:04:59 init() - seeds length: 0
2017/06/17 20:04:59 init() - host count: 0
2017/06/17 20:04:59 robot user-agent: Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
2017/06/17 20:04:59 sending STOP signals...
2017/06/17 20:04:59 waiting for goroutines to complete...
2017/06/17 20:04:59 crawler done.
2017/06/17 20:04:59 Going to resolve URLs...
2017/06/17 20:04:59 Saving the list
2017/06/17 20:04:59 Backuping database
	Error Trace:	crawl_test.go:31
	Error:		Not equal: 
			expected: 1
			received: 0

**Comment by puzanov** [comment]
@shapoglyk 

This issue occurs on the fresh clone of the project. Try to reproduce on the fresh linux box or docker image. Pull the code, create needed configs and run make test -> you will see the error above.

**Comment by shapoglyk** [comment]
The reason of failed test on fresh box was in absence of ./testdata/sites.txt, because this directory is in gitignore.
I added new test.sites.txt with server.com and set usage of this file in tests.

**Comment by puzanov** [comment]
OK
