### ISSUE TITLE
Add new row in the performance table -> Alexa Rank

### ISSUE THREAD

**Issue by puzanov** [maddevsio/spiderwoman#70]
Show Alexa rank on each day. Row should be placed at the bottom.

**Comment by puzanov** [comment]
Performance report doen to show any info when there is no Alexa rank on the host

**Comment by puzanov** [comment]
Fixed.
Need test for this @belek

**Comment by belek** [comment]
Error occurred in Javascript code, we can't test it with Go. For testing errors in Javascript we need to use some kind of Javascript test frameworks, like Mocha. 

But I added tests, checking that method returning grabber data has no errors and returned proper data.
