### ISSUE TITLE
Add whois grabber

### ISSUE THREAD

**Issue by puzanov** [maddevsio/spiderwoman#71]
Find golang lib, integrate and show the last full output below the performance table (e.g. do not put a row).

**Comment by belek** [comment]
Changed `data` field in table `grabber_data` to type `text`.
Added migration script - checks if `data` type is `varchar`, then change it to `text`.

Added Whois grabber. Getting data from whois using "github.com/domainr/whois", saving it and displaying at performance report.

Renamed function `CreateDBIfNotExists` to `CreateDBIfNotExistsAndMigrate`

**Comment by puzanov** [comment]
Tests not working
2017/10/28 11:49:49 "Error 1007: Can't create database 'spiderwoman-test'; database exists": DROP DATABASE IF EXISTS `spiderwoman-test`; CREATE DATABASE `spiderwoman-test`;

**Comment by puzanov** [comment]
2017/10/28 11:49:50 Error 1146: Table 'spiderwoman-test.grabber_data' doesn't exist

**Comment by puzanov** [comment]
Now working. Looks like temporary errors with Mysql in Docker.
